export const blogCanonicalSlugs: Record<string, string> = {
    "citizens-property-insurance-florida-eligibility-your-2025-gu": "citizens-insurance-florida-eligibility-requirements-2026-gui",
    "citizens-insurance-florida-eligibility-complete-2025-guide": "citizens-insurance-florida-eligibility-requirements-2026-gui",
    "citizens-insurance-florida-eligibility-2026-update-guide": "citizens-insurance-florida-eligibility-requirements-2026-gui",
    "citizens-insurance-florida-eligibility-2026-complete-guide": "citizens-insurance-florida-eligibility-requirements-2026-gui",
    "florida-pip-coverage-explained-what-every-north-florida-driv": "florida-pip-coverage-explained-what-you-need-to-know-for-202",
    "florida-pip-coverage-explained-your-complete-guide-for-2026": "florida-pip-coverage-explained-what-you-need-to-know-for-202",
    "florida-nofault-insurance-2026-what-changes-mean-for-drivers": "florida-nofault-insurance-2026-what-lake-city-drivers-must-k",
    "florida-roof-insurance-requirements-your-2026-complete-guide": "florida-roof-insurance-requirements-2026-new-laws-and-rules-",
    "florida-roof-insurance-requirements-guide-for-2026": "florida-roof-insurance-requirements-2026-new-laws-and-rules-",
    "florida-roof-insurance-requirements-your-2026-guide-to-cover": "florida-roof-insurance-requirements-2026-new-laws-and-rules-",
    "florida-roof-insurance-requirements-2026-guide-for-homeowner": "florida-roof-insurance-requirements-2026-new-laws-and-rules-",
    "florida-wind-mitigation-savings-how-north-florida-homeowners": "florida-wind-mitigation-savings-your-complete-guide-to-insur",
    "florida-wind-mitigation-savings-your-guide-to-lower-home-ins": "florida-wind-mitigation-savings-your-complete-guide-to-insur",
    "florida-hurricane-deductible-guide-understanding-your-costs": "florida-hurricane-deductibles-complete-2026-guide-for-homeow",
    "florida-hurricane-deductibles-explained-what-you-need-to-kno": "florida-hurricane-deductibles-complete-2026-guide-for-homeow",
    "florida-sr22-insurance-complete-guide-for-north-florida-driv": "florida-sr22-insurance-your-complete-guide-to-requirements-a",
    "florida-sr22-insurance-complete-guide-for-2026-requirements-": "florida-sr22-insurance-your-complete-guide-to-requirements-a",
}
